- name: 'Deploy minigoodreads-be to k8s'
  hosts: gcloud-k8s
  tasks:
      - name: 'Delete spring-deployment from k8s'
        kubernetes.core.k8s:
            namespace: default
            name: minigoodreads-be
            api_version: apps/v1
            kind: Deployment
            state: absent
      - name: 'Apply spring-deployment to k8s'
        kubernetes.core.k8s:
            state: present
            namespace: default
            template: '../files/k8s-templates/spring-deployment.j2'
